#spring.application.name=User-Task-Service

#  spring.jpa.hibernate.ddl-auto=update
#  spring.datasource.url=jdbc:mysql://localhost:3306/mydatabase
#  spring.datasource.username=myuser
#  spring.datasource.password=secret
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true
server:
  port: 5002

spring:
  application:
    name: Task-Service
  #    it is the file name for the eureka to find
  jpa:
    hibernate:
      ddl-auto: update
  #    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/taskzy_taskservice
    username: root
    password: 2106@2308Ud
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/




